### PR TITLE
Adding Build resource documentation

### LINKED ISSUE #1130: Improve documentation for Build resource
We've gotten feedback that it would be helpful to provide users with documentation on how [the Build resource](https://github.com/pivotal/kpack/blob/main/docs/build.md) can be used to achieve a one-off build experience, similar to `pack build` 

We should provide documentation on how users can leverage the build resource to provide an imperative build experience. 

**Note:** Some users of the `Build resource` are likely `pack` users looking to the `Build` resource as a way to get started with kpack. As such, we should make this documentation as beginner-friendly as possible :)

### PR DESCRIPTION
**Pull request by jjbustamante**
This PR adds some documentation to help understand users on how they achieved a similar outcome from a `pack build` using `Build` resource 

Fixes #1130

### CODE REVIEW

**Comment by samj1912** [comment]
@jjbustamante can we add some docs on how to rebuild/rebase with the build resource?

**Comment by jjbustamante** [comment]
> @jjbustamante can we add some docs on how to rebuild/rebase with the build resource?

Yeah, I will do that next week

**Comment by jjbustamante** [comment]
> @jjbustamante can we add some docs on how to rebuild/rebase with the build resource?

@samj1912 , I added some docs for rebuild and rebase, if can take a look it will be great

**Comment by hone** [comment]
@jjbustamante what are your thoughts on moving this out and into it's own tutorial?

**Comment by jjbustamante** [comment]
> @jjbustamante I noticed there is more than 1 kpack tutorial. What are your thoughts on moving this out the Build docs and into it's own tutorial? It'd still be great to reference it from there.

I don't have problem with that, thinking about it, maybe we can add a link in the README, something like:

Screenshot 2023-05-17 at 8 18 50 AM

And keep the link in the build resource page.

@tomkennedy513 , @matthewmcnew  any thoughts on this?

**Review by tomkennedy513 — APPROVED** [review]

**Comment by tomkennedy513** [comment]
> @tomkennedy513 @hone I just updated the PR, let me know how it looks now

@jjbustamante Looks good! Can you just remove the WIP commits for this pr as well

**Comment by jjbustamante** [comment]
> > @tomkennedy513 @hone I just updated the PR, let me know how it looks now
> 
> @jjbustamante Looks good! Can you just remove the WIP commits for this pr as well

Done! @tomkennedy513

**Pull request merged**
