### PR TITLE
allow dev to add prefix to generated image names (for docker.io registry target)

### PR DESCRIPTION
**Pull request by drnic**
```
image_prefix=kpack- ./hack/release.sh drnic tmp/logs-success-msg-release.yml
```

would generate images `drnic/kpack-controller`, `drnic/kpack-build-init`, `drnic/kpack-source-init`

### CODE REVIEW

**Comment by scothis** [comment]
Should there be two values to define the image name? Having a single value control the image prefix would be preferable in my eyes.

**Comment by drnic** [comment]
Yeah probably. I’ll try to come up with something else.
-- 
Dr Nic Williams
Stark & Wayne LLC
http://starkandwayne.com
+61 437 276 076
twitter @drnic

**Comment by drnic** [comment]
@scothis better?

I'm not sure how to make it truly better without changing the `./hack/release.sh gci.io/registry/path out/release.yml` API; but this requires changing your CI.

**Comment by ashwin-venkatesh** [comment]
@drnic merged master into the branch by accident. Apologies.

**Comment by drnic** [comment]
@ashwin-venkatesh  Rebased against master (for good measure) and force pushed

**Pull request merged**
