### PR TITLE
Add a section for Builder/ClusterBuilder field descriptions

### PR DESCRIPTION
**Pull request by thephw**
### Changelog
* Add sections for Builder/ClusterBuilder field descriptions
* Add annotations for required or optional field
* Add annotations for default values

Signed-off-by: Patrick Wiseman <patrick.wiseman@deft.services>

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@thephw Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal/kpack&pullRequestId=306)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal/kpack&pullRequestId=306) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@thephw Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal/kpack&pullRequestId=306)!

**Comment by thephw** [comment]
Happy to help 🎉

**Comment by djoyahoy** [comment]
Hey @thephw, can you please update the branch and we can merge. Thanks!

**Comment by thephw** [comment]
_updating_

**Pull request merged**
