### PR TITLE
Add note to check the logs

### PR DESCRIPTION
**Pull request by dmikusa-pivotal**
This helped me to spot an issue where kpack-controller didn't start up correctly. Maybe worth adding to the instructions?

### CODE REVIEW

**Comment by matthewmcnew** [comment]
@dmikusa-pivotal What issue did you run into where the controller didn't start correctly?

**Comment by dmikusa-pivotal** [comment]
@matthewmcnew - Sorry, I should have copied the message down to have the exact message. What ended up happening was that my minikube was in a bad state, containers couldn't connect to the API. When you'd try it would timeout. The kpack-controller would start and run, but the logs had a bunch of i/o timeout errors as it was trying to talk to the API. It wasn't clear what was happening until I looked at the logs for kpack-controller, which is why I thought that might be a helpful troubleshooting step.

For what it's worth, the issue was totally my minikube env. I had to blow it away and recreate it.

**Comment by joaopapereira** [comment]
@dmikusa-pivotal can you please rebase your branch with latest master?

**Comment by dmikusa-pivotal** [comment]
@joaopapereira - Did that do it?

**Comment by ashwin-venkatesh** [comment]
@dmikusa-pivotal The commits in the PR look wrong 🤔

**Comment by dmikusa-pivotal** [comment]
OK, let me just resubmit.

**Pull request closed without merging**
