### PR TITLE
update slack info in README

### PR DESCRIPTION
**Pull request by tomkennedy513**

### CODE REVIEW

**Review by tylerphelan — APPROVED** [review]

**Comment by matthewmcnew** [comment]
Do we want to encourage k8s slack over the CNCF slack (when buildpacks move)?

**Comment by tomkennedy513** [comment]
> Do we want to encourage k8s slack over the CNCF slack (when buildpacks move)?

My understanding is that kpack would not be able to move to the cncf slack

**Comment by matthewmcnew** [comment]
I think they just wouldn't automatically migrate it but, we could create a kpack channel.

**Comment by tomkennedy513** [comment]
Oh I must have misunderstood then. I thought kpack had to be in the cncf to have a channel there

**Comment by matthewmcnew** [comment]
My take would be wait until the CNB slack is migrated and then decide where we would prefer the "official" channel to live.

**Comment by samj1912** [comment]
You should be able to create a slack channel in the cncf slack. It's just that we can't migrate it along with the rest of the project I believe.

**Review by dumez-k — APPROVED** [review]

**Review by matthewmcnew — APPROVED** [review]

**Pull request merged**
