### PR TITLE
add a non-tailing version of fetching logs for an image

### PR DESCRIPTION
**Pull request by LukeWinikates**
👋 Hi there. Fellow 'Pivotal' team here.

We're looking to fetch kpack logs and get just the logs available now for the containers currently running. None of the existing `Tail*` functions supported that use case, but we were able to figure out how to accomplish what we needed by adding more boolean flags.

We'd like to see if we can get this merged so that we can eliminate our fork as a dependency. This shouldn't change the behavior of any of the existing functions in the package.

It does start to clutter up the function signatures with boolean flags.

Curious to hear any feedback about the `GetImageLogs` function name - `Tail` doesn't seem appropriate, since we're not trying to tail the logs in this case.

Thanks in advance,
@LukeWinikates  / @ssama-pivotal

### CODE REVIEW

**Review by tylerphelan — APPROVED** [review]
I like it!

**Comment by LukeWinikates** [comment]
I just pushed an updated version of this commit - the changes in the original version ended up not being sufficient, as `watchReadyContainers` was also waiting for all of the pods to finish their work. The commit I just pushed reflects what we're currently using for Iris. If this code or some version of this feature could be merged, that would be great for the Iris team as we'd be able to eliminate our fork. Thanks for considering!

**Review by matthewmcnew — APPROVED** [review]

**Comment by matthewmcnew** [comment]
@LukeWinikates Could you rebase and we will merge?

**Comment by LukeWinikates** [comment]
@matthewmcnew done!

**Pull request merged**
