### PR TITLE
Add Ability to Strip Components from Blob Files

### PR DESCRIPTION
**Pull request by diarmuidie**
### What:

This change adds a new field to the blob source that lets you specify the number of base directory components you want to strip from the path when extracting the files. This is similar in functionality to the the tar `--strip-components` argument.

The field will default to `0` so that if it is not set the existing build functionality is unchanged.

### Why:

You might be receiving an archive blob from a third party in your build, where you have no prior knowledge of the parent directory name so you can't use the `subPath` option to specify the root. For example when using [Githubs archive API](https://docs.github.com/en/rest/repos/contents#download-a-repository-archive-tar) the parent directory's name depends on if the repo is public or private, using Github Enterprise server or not etc. With this change you don't need to know the details but can tell kpack to strip 1 component when extracting and that will put the working dir for the build in the root of the repo archive.

Fixes: https://github.com/pivotal/kpack/issues/957

### CODE REVIEW

**Review by tylerphelan — APPROVED** [review]
nice! thank you!

**Review by ncarlson — APPROVED** [review]
Looks good! Thank you for the contribution.

**Review by jjbustamante — APPROVED** [review]
Looks good! 
I also ran the test locally and everything is fine. I just did it because the job is pending on github.

Great job @diarmuidie !

**Comment by diarmuidie** [comment]
> Looks good! I also ran the test locally and everything is fine. I just did it because the job is pending on github.
> 
> Great job @diarmuidie !

Thanks @jjbustamante . Looks like the tests aren't running because I'm a first time contributor:
> 1 workflow awaiting approval
> First-time contributors need a maintainer to approve running workflows

**Review by ncarlson — APPROVED** [review]

**Review by tomkennedy513 — APPROVED** [review]

**Review by matthewmcnew — APPROVED** [review]

**Comment by matthewmcnew** [comment]
Thanks so much @diarmuidie !

**Pull request merged**
