### PR TITLE
Print a 'Build Successful' at the end of log output

### PR DESCRIPTION
**Pull request by matthewmcnew**
- Include steps in cyan in log output to match pack output
- Improves output as proposed in: #149, #147

### CODE REVIEW

**Comment by matthewmcnew** [comment]
@drnic If you have a moment, I am curious what your thoughts are with this log output.

**Comment by drnic** [comment]
@matthewmcnew I'm away from good internet to `pack build` + push the branch. Do you have a screenshot?

If I'm reading the code right, it says to use `red` for the success message. Perhaps green for success? :)

**Comment by matthewmcnew** [comment]
Whoops that should not be in red. It displays the step in name in cyan. Hopefully, similar to the pack output. 

Something like this:

**Comment by drnic** [comment]
It looks lovely indeed. Nice to see the stage prefixes added into the logs
too.
-- 
Dr Nic Williams
Stark & Wayne LLC
http://starkandwayne.com
+61 437 276 076
twitter @drnic

**Comment by drnic** [comment]
I've built `logs` locally and it looks great. Thanks!

**Comment by joaopapereira** [comment]
@matthewmcnew please rebase this PR

**Pull request merged**
